### ISSUE TITLE
Buy not working

### ISSUE THREAD

**Issue by lwieseke** [pladaria/degiro#21]
results.data needs to be changed to results.products

const returnFirstProductResult = result => {
        if (Array.isArray(result.products) && result.products.length) {
            return result.products[0];
        }
        throw new Error('Product not found');
    };

**Comment by Drag0s** [comment]
You should update your `degiro` library to the newest version. The `buy` method was deprecated and now you should use `setOrder` instead.

You can check a working example with this new method [here](https://github.com/pladaria/degiro/blob/master/examples/buy.js) and its [specification](https://github.com/pladaria/degiro#setorder-buysell).

**Comment by Drag0s** [comment]
This piece of coude you pasted it's from a older library version. You should update your `degiro` library to the newest version. The `buy` method was deprecated and now you should use `setOrder` instead.

You can check a working example with this new method [here](https://github.com/pladaria/degiro/blob/master/examples/buy.js) and its [specification](https://github.com/pladaria/degiro#setorder-buysell).


Also, it's true that in the [README](https://github.com/pladaria/degiro#searchproduct) it still says `data` instead of `products`
